#!/usr/bin/env python3
"""
Oppdaterer reason-feltet for titler/rang i person_roles med forhåndsgenererte beskrivelser.
Kjøres én gang. Ingen API-nøkkel nødvendig.
"""

import os, sys, warnings
warnings.filterwarnings('ignore')

try:
    from supabase import create_client
except ImportError:
    print("Mangler supabase-pakke. Kjør: pip install supabase")
    sys.exit(1)

SUPABASE_URL = os.environ.get("SUPABASE_URL", "https://xxddcdwaixlstyderylv.supabase.co")
SUPABASE_SERVICE_KEY = os.environ.get("SUPABASE_SERVICE_KEY",
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4ZGRjZHdhaXhsc3R5ZGVyeWx2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MzAwMDgxNSwiZXhwIjoyMDg4NTc2ODE1fQ.cUn6ZDvPZ9r-FZe3BEg8VNnSzN9C-sAbw9KASNql4ao"
)

# Forhåndsgenererte beskrivelser: liste av (IDs, beskrivelse)
UPDATES = [
    ([2881, 4714], "Riksgreve (Reichsgraf) var en høyadelig tittel i Det Hellige Romerske Rike som ga innehaveren direkte lydighet under keiseren. Schmettow var en schlesisk adelsfamilie som ble opphøyet til riksgrevelig rang på 1600-tallet. Tittelen medfulgte representasjonsrett i riksdagen og betydelige arvelige rettigheter."),
    ([12359, 12436, 12439], "Kammerherre var en høy hofftittel ved europeiske kongelige hoff som opprinnelig betegnet den som hadde adgang til fyrstens private gemakker. Med tiden ble det en æreskitering tildelt adelsmenn av høy rang som symboliserte nærhet til kongemakten. I Danmark-Norge ble tittelen synliggjort med en forgyllt nøkkel på uniformen."),
    ([7625, 7855, 12235], "Kongen av Danmark og Norge hersket over de to rikene i personalunion, med maktsentrum i København. Fra eneveldets innføring i 1660 hadde kongen suverene rettigheter over begge rikene, herunder lovgivende, utøvende og militær myndighet. Den dansk-norske kongen var en av de mest maktfulle monarkene i Norden."),
    ([7629, 8106, 1105, 9150, 9418, 12435], "Greve var en adelig tittel i det europeiske feudale systemet som opprinnelig betegnet en kongelig embedsmann med administrativt ansvar over et grevskap. Tittelen var arvelig og ga innehaveren privilegier, rettslig myndighet over egne undersåtter og sete i aristokratiets råd. I Danmark-Norge var grevene blant de høyeste i adelshierarkiet og eide ofte store godser."),
    ([7816, 8301], "Kongen av Danmark var den øverste hersker i det danske kongedømme, med absolutt myndighet etter innføringen av eneveldet i 1660. Kongen styrte gjennom et sentralisert embetsverk og var øverste myndighet i kirke, hær og rettsapparat. Det danske kongedømme var et av de eldste dynastiske monarkier i Europa."),
    ([7842, 7868], "Dronningen av Danmark var enten herskerinne i egen rett eller – langt oftere – gjennom ekteskap den fremste kvinne i det danske kongehuset. Som regent hadde dronningen full kongelig myndighet, men i praksis regjerte de fleste dronninger i kraft av sin posisjon som kongens hustru og mor til tronfølgeren. Dronningen hadde stor innflytelse på hofflivet og diplomatiske ekteskapsforhandlinger."),
    ([12395, 12396], "Dronning konsort var betegnelsen på en regjerende konges dronning uten selvstendig statsmakt. Hun nøt kongelig rang, privilegier og ceremonielle oppgaver ved hoffet, men hadde ikke formell myndighet over rikets styre. I praksis hadde mange dronninger konsort stor uformell innflytelse gjennom nærhet til kongen og rollen som mor til tronfølgeren."),
    ([7909, 7917, 7925, 7934, 7958, 7980], "Grevinne var enten tittel for en grevens hustru eller for en kvinne som selv innehadde et grevskap i arv. Tittelen ga høy sosial rang og privilegier, men sjelden direkte politisk myndighet med mindre hun styrte på vegne av en mindreårig sønn. Grevinnen hadde ansvar for hoffholdning, familieallianser og godsdrift."),
    ([7943], "En grevinne av Slesvig-Holsten tilhørte adelen knyttet til hertugdømmene Slesvig og Holstein ved den sørlige grensen av det danske kongedømme. Disse hertugdømmene var nær knyttet til den danske krone, men hadde egne rettslige og administrative tradisjoner. En grevinne der nøt høy rang i det dansk-tyske adelshierarkiet."),
    ([8028], "Kurfyrstinne konsort av Sachsen og Meissen var den regjerende kurfyrste av Sachsens hustru og bar høy rang i Det Hellige Romerske Rike. Sachsen var et av de viktigste kurfyrstendømmene med rett til å delta i keiservalget. Meissen utgjorde kjernen i det wettinske kurfyrstedømmet, og kurfyrstinnen spilte en sentral rolle i hofflivet og dynastiske allianser."),
    ([12403], "Hertug av Cumberland var en britisk adels- og kongelig tittel tildelt prinser av det britiske kongehuset. Tittelen ga høy rang og var knyttet til Cumberland-regionen i nordvest-England, men innebar ikke reell administrativ kontroll over området. Hertuger av Cumberland ble vanligvis utnevnt blant kongssønnene for å sikre dem passende titulær rang."),
    ([12404], "Prins av Danmark var tittel for sønner eller nære mannlige slektninger av den danske kongen. Tittelen ga kongelig rang og privilegier ved hoffet, men ikke formell regjeringsmyndighet med mindre prinsen var kronprins. Danske prinser fikk ofte militære kommandoer eller administrativt ansvar over deler av riket."),
    ([12405], "Prins konsort var betegnelsen på en regjerende dronnings ektefelle i Storbritannia og bar kongelig rang uten formell statsmakt. Tittelen erkjente ektefellens kongelige opphav, men plasserte vedkommende under dronningen i den konstitusjonelle rangsordningen. Prins konsorten støttet tradisjonelt dronningens offisielle funksjoner og representasjon."),
    ([8713, 12410, 12411, 9664], "Kurfyrsten av Brandenburg var en av de syv (senere ni) kurfyrstene i Det Hellige Romerske Rike med rett til å velge keiser. Brandenburg-kurfyrstene, av slekten Hohenzollern fra 1415, styrte markgrevskapet Brandenburg og ervervet fra 1618 hertugdømmet Preussen, som la grunnlaget for den fremtidige preussiske staten. Kurfyrsten var blant de mektigste fyrstene i riket."),
    ([8734], "Hertugen av Kleve styrte hertugdømmet Kleve ved Rhinen, et strategisk viktig territorium ved grensen til Nederland. Hertugdømmet ble etter en arvefeidestrid i 1614 delt mellom Brandenburg og Pfalz-Neuburg, og Hohenzollerne fikk Kleve, Mark og Ravensberg. Kleve-hertugen hadde kontroll over viktige handelsruter og Rhinens nedre løp."),
    ([8942], "Hertugesse av Pommern var enten en regerende hertuginne eller hertug av Pommerns hustru. Pommern var et baltisk kystland med viktige handelsbyer, delt mellom Sverige og Brandenburg-Preussen etter Tredveårskrigen (1618–1648). Hertugesser av Pommern ble brukt i dynastiske allianser mellom nord-europeiske fyrstehus."),
    ([12296], "Hertugesse av Sachsen-Lauenburg var hertugens hustru eller en regerende hertuginne av dette lille nord-tyske hertugdømmet mellom Elben og Holstein. Sachsen-Lauenburg var et arvestykke av Welferdynastiet og ble i 1689 innlemmet i Hannover. Hertugesser derfra var ettertraktede som ekteskapspartnere for nordeuropeisk adel."),
    ([11459, 12264, 12266, 12268], "Kongen av Polen ble valgt av den polske adelen (szlachta) gjennom den unike valgmonarkiordningen. Kongen hadde begrenset makt sammenlignet med andre europeiske monarker, da adelen hadde sterk innflytelse gjennom Sejmen og liberum veto, der en enkelt adelsmann kunne stanse lovgivningen. Polen var likevel en europeisk stormakt på 1500- og 1600-tallet."),
    ([12431], "Landgrevinne av Hessen var enten herskerinne i landgrevskapet Hessen eller landgrevens hustru. Hessen var et protestantisk fyrstendømme i Mellom-Tyskland som spilte en viktig rolle under reformasjonen og Tredveårskrigen. Tittelen landgreve (og grevinne) var høyere enn vanlig hertug i det tyske rangsystemet."),
    ([12072], "Kongen av Böhmen og Ungarn styrte disse to kongedømmene i personalunion under Habsburgdynastiet. Böhmen ga kongen rett til å delta i keiservalget som kurfyrste, mens Ungarn var Europas forsvarsvokt mot det osmanske riket. Habsburgerne konsoliderte makten over begge riker etter slaget ved Mohács i 1526."),
    ([12432], "Hertug av Østerrike var den opprinnelige tittelen til Habsburgerne frem til de ble erkehertug på 1300-tallet. Østerrike var kjernen i habsburgsk makt og grunnlaget for Det Hellige Romerske Rikes keiserdynasti. Med tidens gang ble 'hertug av Østerrike' underordnet tittelen 'erkehertug', som alle mannlige Habsburgere bar."),
    ([1083, 6992], "Riksgrevinne (Reichsgräfin) var en adelig tittel i Det Hellige Romerske Rike, enten for en riksgrevs hustru eller for en kvinne som selv innehadde et riksgrevskap. Tittelen ga umiddelbar keiserlig lydighet og representasjonsrett i riksdagen gjennom grevenes kollegium. Riksgrevinners rang var høyere enn vanlige grevinners, siden lydigheten lå direkte under keiseren."),
    ([1122, 8293, 9429, 9435], "Komtesse var tittelen for en ugift datter av en greve eller riksgreve i det kontinentale adelshierarkiet. Tittelen hadde ingen forrettningsmessig maktfunksjon, men ga høy sosial rang og åpnet for posisjoner ved hoffet. Komtesser ble brukt aktivt i dynastiske ekteskapsstrategier mellom europeiske adelsfamilier."),
    ([2841], "Baronesse var tittelen for en ugift datter av en baron eller for en barons hustru. Tittelen plasserte innehaveren lavere i adelshierarkiet enn grevinnene, men ga likevel privilegier og sosial distinksjon i det europeiske aristokratiet. Baronesser deltok i hofflivet og ble brukt i ekteskapsallianser mellom lavere adel."),
    ([2905], "En komtesse av Schmettow var en ugift datter av den riksgrevelige Schmettow-familien fra Schlesien. Familien hadde oppnådd riksgrevelig rang og hadde godser i det schlesiske adelsskapet som etter 1742 kom under prøyssisk styre. Komtessens rang fulgte familiens status som riksgrever i Det Hellige Romerske Rike."),
    ([7985], "Hertugesse konsort av Braunschweig var hertug av Braunschweig-Wolfenbütels hustru. Braunschweig var et welfisk hertugdømme i Nord-Tyskland, og familien var ett av Europas eldste dynastier med røtter til Henrik Løven på 1100-tallet. Hertugesser fra Braunschweig var ettertraktede ekteskapspartnere, og dynastiet ga opphav til kongehusets hannoverske linje i Storbritannia."),
    ([8019, 8315], "Hertugesse konsort av Holstein-Gottorp var hertug av Holstein-Gottorps hustru. Gottorp-linjen var en sidelinje av det danske kongehus som styrte den gottorpske halvdelen av hertugdømmene Holstein og Slesvig, i motsetning til den kongelige danske halvdelen. Holstein-Gottorp-dynastiet fikk stor europeisk innflytelse da det ga opphav til den russiske keiserfamilien Romanov-Holstein-Gottorp."),
    ([8310, 7996], "Prinsesse av Danmark var tittel for en kongsdatter eller nær kvinnelig slektning av den danske kongen. Tittelen ga kongelig rang og var et viktig diplomatisk redskap i ekteskapsforhandlinger mellom europeiske kongehus. Danske prinsesser ble gift inn i tyske, svenske, britiske og russiske dynastier."),
    ([8324], "Kurfyrstinne konsort av Pfalz var kurfyrste av Rhin-Pfalz' hustru. Pfalz var et av de opprinnelige sju kurfyrstendømmene i Det Hellige Romerske Rike og lå langs Rhinens vestbredder med Heidelberg som residensby. Kurfyrstinnen av Pfalz hadde høy rang i riket og spilte en sentral rolle i kulturlivet ved det berømte Heidelberg-hoffet."),
    ([8724, 9933], "Kurfyrstinne av Brandenburg var enten kurfyrstens hustru eller – i sjeldne tilfeller – en regerende kurfyrstinne. Brandenburg var et av de viktigste kurfyrstendømmene i Det Hellige Romerske Rike med avgjørende stemme ved keiservalg. Kurfyrstinnene av Hohenzollern-ætten inngikk viktige dynastiske ekteskap og bidro til slektens voksende maktposisjon i Nord-Tyskland."),
    ([8922], "Markgreve av Brandenburg-Bayreuth styrte Bayreuth-territoriet, en del av de frankiske Hohenzollern-markgrevskapene i det sørlige Germany. Bayreuth var et av de to frankiske markgrevskapene (sammen med Ansbach) der Hohenzollern-sidelinjer hersket frem til de falt tilbake til det preussiske kongedømmet. Residensbyen Bayreuth er i ettertiden kjent for sine barokke palasser og Richard Wagners operafestival."),
    ([8923], "Markgreve av Brandenburg in Bayreuth styrte det frankiske territoriet Bayreuth som en Hohenzollern-sidelinje av kurfyrstehuset Brandenburg. Bayreuth-linjen og Ansbach-linjen utgjorde de frankiske markgrevskapene der Hohenzollern-prinser regjerte som relativt selvstendige fyrster. Begge territorier ble i 1792 innlemmet i det preussiske kongedømmet."),
    ([8930, 8931], "Landgrevinne av Hessen-Darmstadt var enten herskerinne i landgrevskapet Hessen-Darmstadt eller landgrevens hustru. Hessen-Darmstadt var én av de to delene Hessen ble delt i på 1500-tallet (den andre var Hessen-Kassel) og var sentrum for en aktiv dynasti som inngikk mange europeiske ekteskapsallianser. Landgrevinnen spilte en viktig rolle i dynastisk politikk og hoffkultur."),
    ([8937], "Markgreve av Brandenburg-Ansbach styrte Ansbach-territoriet i Franken, det andre av de to frankiske Hohenzollern-markgrevskapene. Ansbach lå i det sørlige Franken og var residenssby for en sidelinje av Hohenzollern-dynastiet fra 1398 til 1791. Markgrevskapet ble i 1791 solgt til Preussen da den siste markgreven abdiserte."),
    ([8943], "Prinsesse av Brandenburg var tittel for en datter av Hohenzollern-kurfyrstefamilien i Brandenburg. Brandenburgske prinsesser ble flittig brukt i politiske ekteskapsallianser med andre tyske fyrstehus og europeiske dynastier som ledd i Hohenzollernenes maktutvidelse. Prinsessene representerte dynastiet ved utenlandske hoff og spilte en viktig rolle i diplomatiet."),
    ([8950], "Prinsesse var en kongelig eller fyrstelig tittel for kvinner av dynastisk blod, brukt over hele Europa. Tittelen ga høy rang i det adelige hierarkiet og var avgjørende for dynastiske ekteskapsforhandlinger. Prinsesser ble brukt aktivt i alliansebygging mellom fyrstehus og ble opplært i hoffetikette og fremmede språk fra tidlig alder."),
    ([11383, 12237, 12281], "Hertugesse av Sachsen var enten en regerende hertuginne eller hertug av Sachsens hustru innen Wettiner-dynastiets mange linjer. Sachsen var delt mellom tallrike hertugelige sidelinjer, og hertugesser spilte viktige roller i dynastiske forbindelser mellom de tyske fyrstehusene. Sachsens rikdom fra sølvminer og handel gjorde titelen attraktiv i europeisk dynastipolitikk."),
    ([11409], "Kongen av Böhmen var en valgmonark valgt av de böhmiske stendene, med en av Europas mest prestisjefylte kongestitler. Tittelen ga rett til å delta i keiservalget som kurfyrste i Det Hellige Romerske Rike, noe som gjorde Böhmen til ett av de politisk viktigste kongedømmene. Fra 1526 ble tronen i praksis arvelig for Habsburgerne."),
    ([8206], "Greve av Laurvig og Herzhorn styrte grevskapet Laurvig (Larvik) i det nåværende Vestfold og Herzhorn i Holstein som lensherre under den dansk-norske kronen. Grevskapet Laurvig var ett av de siste danske grevskaper på norsk jord, opprettet på 1600-tallet og med kontroll over store skogeiendommer og jernverk. Herzhorn var et tilhørende gods i Holstein."),
    ([12438], "Lensgreve var en dansk-norsk adelig tittel for innehavere av et grevskap som len fra kongen. Lensgrever hadde juridisk og administrativ myndighet over sine lensundersåtter og var forpliktet til å yte tjeneste til kongen. Systemet med lensgrever var en del av det eneveldige Danmarks forsøk på å kontrollere aristokratiet ved å gjøre dem avhengige av kongelig nåde."),
    ([12440], "Gehejmekonferensråd var en av de absolutt høyeste hofftitlene i Danmark-Norge under eneveldet, over gehejmeråd i rangsordningen. Tittelen ble tildelt de fremste statsmenn, hoffmenn og diplomater som bevis på kongelig gunst og nærhet til maktens sentrum. Gehejmekonferensrådets tittel ga rett til spesielle privilegier og høy protokollarisk rang ved det kongelige hoff."),
    ([12441], "Greve av Danmark-Norge styrte et grevskap under den dansk-norske kongen som len. I motsetning til tyske riksgrever, som lydde direkte under keiseren, var disse grevene underlagt den danske kongen og fikk sin rang og privilegier fra ham. Systemet ble brukt til å belønne adelige og militære tjenester og knytte den høye adelen til kongemakten."),
    ([12446], "Dronning konsort av Skottland var den skotske kongens dronning. Skottland hadde eget kongehus frem til unionen med England i 1603, og dronningene kom ofte fra franske og skandinaviske dynastier som ledd i diplomatiske allianser. Dronning konsortens rolle var å støtte kongen, produsere en arving og representere kongemagtens verdighet."),
    ([12226], "Baron av Løvendal var innehaveren av baroniett Løvendal i Danmark. Løvendal var et dansk adelsgods og tittelen var en av de lavere adelstitler i det dansk-norske hierarkiet, under greve men over alminnelig adel. Baroniet ga innehaveren myndighet over sine undersåtter og forpliktet til militær tjeneste for kongen."),
    ([12227, 12233], "Prinsesse av Danmark og Norge var tittel for kongsdøtre i den dansk-norske unionsstat. Prinsessene ble brukt i dynastiske allianser med andre europeiske hoff, særlig tyske fyrstehus, som ledd i dansk-norsk utenrikspolitikk. Tittelen ga kongelig rang og krav på apanasje fra statskassen."),
    ([12228, 12229, 12230, 12254], "Prins av Danmark og Norge var tittel for kongssønner som ikke var kronprinser, i den dansk-norske stat. Prinsene fikk militære kommandoer, hertugelige apanasjer eller administrative embeter og spilte viktige roller i hoffliv og diplomati. Tittelen var arvelig fra dynastiet og forpliktet prinsene til å støtte kongehusets interesser."),
    ([12231], "Hertug av Slesvig-Holstein styrte hertugdømmene Slesvig og Holstein, som var komplekst forbundet med den danske krone. Slesvig var et dansk len mens Holstein var et tysk len under Det Hellige Romerske Rike, noe som skapte vedvarende konstitusjonelle spenninger. Disse hertugdømmene var gjenstand for gjentatte arvekonflikter som til slutt resulterte i krigen i 1864."),
    ([12232], "Kronprins av Danmark og Norge var den offisielle tronarvingen til det dansk-norske kongedømmet. Kronprinsen ble forberedt for regjeringsansvaret gjennom militær utdanning, reiser og deltakelse i statsanliggender. I store perioder fungerte kronprinsen som regent når kongen var fraværende eller svekket."),
    ([12234, 12249], "Hertug av Preussen styrte hertugdømmet Preussen øst for Vistula, opprinnelig Tyske Ordens ordensstat som ble sekulært hertugdømme i 1525. Preussen var opprinnelig et polsk len, men ble gjort suverent under Hohenzollerne i 1618 og i 1701 opphøyet til kongerike. Preussens øst-baltiske beliggenhet ga strategisk betydning i handelen med Russland og Polen."),
    ([12236, 12244, 12245, 12246, 12248, 12252, 12256, 12257, 12258, 12259, 12260, 12261, 12262], "Markgreve av Brandenburg var herskeren over markgrevskapet Brandenburg, et grenseområde (mark) nord for det tyske kjerneområdet. Fra 1356 var markgreven av Brandenburg kurfyrste i Det Hellige Romerske Rike med rett til å delta i keiservalget. Hohenzollern-dynastiet overtok markgrevskapet i 1415 og bygde det opp til kjernen i det fremtidige preussiske kongedømmet."),
    ([12238, 12239, 12240, 12241, 12242, 12243], "Markgrevinne av Brandenburg var kurfyrstens hustru i det mektige kurfyrstendømmet Brandenburg. Som kurfyrstinne hadde hun høy rang i Det Hellige Romerske Rike og spilte en viktig rolle i det hohenzollernske hofflivet og dynastiske ekteskapsstrategier. Markgrevinnen av Brandenburg var en av de mest ettertraktede ekteskapspartnere for protestantisk adel i Nord-Europa."),
    ([12247], "Dronning av Ungarn var enten herskerinne i eget navn eller den ungarske kongens hustru. Ungarn hadde lenge vært et selvstendig kongedømme, men etter den osmanske invasjonen og slaget ved Mohács i 1526 ble det habsburgsk, med store deler okkupert av osmanene. Dronninger av Ungarn hadde stor symbolsk betydning for det splittede kongeriket."),
    ([12250], "Markgreve av Brandenburg-Jägerndorf styrte territoriet Jägerndorf (nå Krnov i Tsjekkia) i Schlesien, som Hohenzollerne hadde arvet gjennom Ansbach-linjen. Jägerndorf var et protestantisk fyrstendømme i et religiøst splittet Schlesien. Etter Tredveårskrigen ble hertugdømmet konfiskert av den habsburgske keiseren som straff for deltakelse på protestantenes side."),
    ([12251], "Hertug av Brandenburg-Jägerndorf styrte det schlesiske Jägerndorf-territoriet som en Hohenzollern-sidelinje. Etter Tredveårskrigen ble hertugdømmet konfiskert av keiseren da den siste hertugen hadde støttet protestantenes opprør. Territoriet ble ikke tilbakelevert til Preussen før Schlesien som helhet ble annektert av Fredrik den store i 1742."),
    ([12253], "Erkebiskopen av Magdeburg var leder for erkebispedømmet Magdeburg, ett av de viktigste kirkelige og politiske sentrene i nord-tyske territorier. Som riksfyrste hadde erkebiskopen sete i riksdagen og administrerte store kirkelige og verdslige territorier langs Elben. Magdeburg-erkebispedømmet ble sekulært etter Tredveårskrigen og omgjort til hertugdøm under Brandenburg."),
    ([12255], "Greve av Oldenburg styrte grevskapet Oldenburg ved Nordsjøkysten i nord-vest Tyskland. Oldenburg-dynastiet var en av de mest innflytelsesrike slektene i europeisk dynastihistorie og ga opphav til kongshus i Danmark, Norge, Sverige, Russland, Hellas og Storbritannia. Grevene av Oldenburg utviklet sitt lille grevskap til et knutepunkt for dynastisk politikk."),
    ([12263, 12276], "Hertug av Sachsen var innehaver av ett av de mange sachsiske hertugdømmene, delt mellom Wettiner-dynastiets mange linjer. Sachsen hadde rik kulturhistorie, stor velstand fra sølvminer og handel, og var sentrum for reformasjonen under Luther. De sachsiske hertugene spilte en avgjørende rolle i tysk politikk, religion og kultur gjennom hele tidligmoderne tid."),
    ([12265], "Prins av Polen var tittel for kongelige prinser i det polsk-litauiske samveldet. I valgmonarkiet Polen hadde prinsene ingen automatisk arverett til tronen, og kongelige barn måtte hevde sin posisjon gjennom diplomatiske og militære midler. Polske prinser fikk ofte titler knyttet til kirkelige embeter eller fyrstelige len i samveldets enorme territorium."),
    ([12267], "Storhertugen av Litauen styrte Storfyrstedømmet Litauen, som i middelalderen var en av Europas aller største stater. Fra Lublin-unionen i 1569 ble Litauen del av det polsk-litauiske samveldet, men storhertugen beholdt sin separate tittel og Litauen hadde egne lover og institusjoner. Polens konger bar samtidig storhertugtittelen av Litauen."),
    ([12269], "Erkebiskopen av Gniezno var den øverste kirkelige leder (primat) i Polen og en av de mektigste geistlige i Øst-Europa. Erkebispedømmet Gniezno var det eldste i Polen, grunnlagt i 1000, og erkebiskopen hadde rett til å krone de polske kongene og fungerte som riksforstander (interrex) i perioden mellom kongedøds og nyvalg. Tittelen ga enorm religiøs og politisk autoritet."),
    ([12270], "Biskopen av Krakow styrte ett av de viktigste bispedømmene i Polen, med Krakow som kongebolig og kulturhovedstad frem til 1596. Biskopen hadde store geistlige og verdslige maktmidler, eide store gods og var en viktig kongelig rådgiver. Krakow-biskopen spilte en nøkkelrolle i polsk kirke- og rikspolitikk."),
    ([12271], "Prinsesse av Polen var tittel for kongelige døtre i det polsk-litauiske samveldet. I valgmonarkiet var polske prinsesser like viktige som i arvemonarkier for dynastiske allianser, og mange ble dronninger i nabolandene Sverige, Russland, Ungarn og de tyske fyrstendømmene. Prinsessens posisjon var avhengig av farens politiske stilling i det konkurransepregede polske aristokratiet."),
    ([12272, 12273, 12274, 12275], "Prins av Sachsen var tittel for sønner av den sachsiske kurfyrste av Wettiner-dynastiet. Sachsen var ett av de rikeste og mest innflytelsesrike fyrstendømmene i Det Hellige Romerske Rike, og sachsiske prinser hadde militære kommandoer og administrative oppgaver. Tittelens prestisje var høy siden Sachsen-kurfyrsten var en av rikets mektigste fyrster."),
    ([12277], "Keiseren av Det Hellige Romerske Rike var den nominelt øverste verdslige hersker i Europa og valgt av kurfyrstene. Keisertittelen ga enorm prestisje og symbolsk myndighet, men i praksis var keiserens faktiske makt over de tyske fyrstene begrenset siden disse var i stor grad autonome i sine egne territorier. Fra 1438 til 1806 var keisertittelen nesten uavbrutt i habsburgernes hender."),
    ([12278], "Prins av Østerrike var tittel brukt om habsburgske prinser, selv om den offisielle dynastiske tittelen fra 1358 var erkehertug. Østerrike var kjernen i habsburgsk makt og utgangspunktet for dynastiets dominans over Det Hellige Romerske Rike. Habsburgske prinser fikk militære kommandoer, riksadministrative embeter og guvernørstillinger i det enorme habsburgske territoriet."),
    ([12279], "Greve av Schmettow tilhørte den schlesiske Schmettow-slekten som hadde oppnådd riksgrevelig rang i Det Hellige Romerske Rike. Familien hadde betydelige godser i Schlesien og spilte en rolle i regionens adelspolitikk. Etter at Preussen annekterte Schlesien i 1742 kom familiens gods under prøyssisk styre."),
    ([12280], "Prinsesse av Polen-Litauen var tittel for kongelige døtre i det forenede polsk-litauiske samveldet. Det store riket dekket deler av dagens Polen, Litauen, Hviterussland og Ukraina, og dets kongelige prinsesser ble brukt i ekteskapsallianser over hele Øst- og Sentral-Europa. Tittelen reflekterte den dobbeltnasjonale karakteren av samveldets statsdannelse."),
    ([12282], "Dronning av Polen var enten den polske kongens hustru eller en herskerinne i eget navn. I valgmonarkiet Polen kom dronningene fra europeiske fyrstehus, og deres diplomatiske bakgrunn og personlige nettverk var viktige ressurser i polsk utenrikspolitikk. Dronningene hadde stor innflytelse ved hoffet og spilte en nøkkelrolle i dynastiske allianser."),
    ([12283], "Storhertuginne av Litauen var tittel for storhertugens hustru i Storfyrstedømmet Litauen. Etter Lublin-unionen i 1569 var tittelen knyttet til dronningtittelen av Polen, siden de to land ble styrt av samme monark. Storhertuginnen hadde høy rang i det polsk-litauiske samveldets hoffhierarki."),
    ([12284], "Erkehertugesse av Østerrike var den offisielle tittelen for habsburgske prinsesser, den kvinnelige ekvivalenten av erkehertug. Erkehertuginner ble hyppig brukt i diplomatiske ekteskaper over hele Europa og bidro til Habsburgdynastiets dominans gjennom en bevisst ekteskapspolitikk oppsummert i ordtaket 'Bella gerant alii, tu felix Austria nube' (La andre føre krig, du lykkelige Østerrike gift deg). Tittelen ga en av Europas høyeste dynastiske ranger."),
    ([12285], "Riksfriherre (Reichsfreiherr) var en adelig tittel i Det Hellige Romerske Rike som ga innehaveren umiddelbar keiserlig lydighet, under riksgreve men over alminnelig territoriell adel. Konigswalde og Haltorf var gods tilhørende denne riksfriherrelinjen i de tyske territoriene. Riksfriherrer hadde representasjonsrett i riksdagens friherrers kollegium."),
    ([12286], "Lensbaron av Løvendal var innehaver av baroniett Løvendal som len fra den dansk-norske kongen. Lenssystemet knyttet adelen til kongemakten gjennom gjensidig forpliktelse: kongen tildelte godset, baronen ytet militær og administrativ tjeneste. Løvendal-familiens dansk-norske len ble holdt av en av Danmarks fremmeste militære dynastier."),
    ([12287, 12289], "Grevinne av Slesvig-Holstein var adelig tittel knyttet til hertugdømmene Slesvig og Holstein. Disse to hertugdømmene hadde komplekse rettslige og dynastiske bånd til både Danmark og Det Hellige Romerske Rike, og grevinnetittelen der ga høy rang i nord-europeisk adelshierarki. Slesvig-Holstein-adelen var tett integrert med det danske kongehuset."),
    ([12288], "Prins av Slesvig-Holstein var tittel for kongelige og hertugelige prinser tilknyttet hertugdømmene Slesvig og Holstein. Slesvig-Holstein-dynastiet hadde nære familiebånd til det danske, svenske, britiske og russiske kongehuset, og prinsene spilte viktige roller i europeisk dynastipolitikk. Tittelen reflekterte det konstitusjonelt komplekse forholdet mellom hertugdømmene og Danmark."),
    ([12292], "Riksgreve av Løvendal (Reichsgraf von Löwendal) var innehaveren av Løvendal-familiens riksgrevelige rang i Det Hellige Romerske Rike. Løvendal-familien hadde forbindelser til det dansk-norske kongehuset og spilte en aktiv rolle i europeisk militærhistorie. Som riksgreve hadde innehaveren direkte keiserlig lydighet og representasjon i riksdagen."),
    ([12309], "Markgraf av Brandenburg er den tyske betegnelsen for markgreve av Brandenburg – herskeren over markgrevskapet Brandenburg. Som kurfyrste av Brandenburg hadde markgrafen rett til å delta i keiservalget, og tittelens tyske form ble brukt i offisielle dokumenter i Det Hellige Romerske Rike. Hohenzollern-dynastiets markgrever bygde Brandenburg opp fra et grenseområde til kjernen i det fremtidige preussiske kongedømmet."),
    ([12310], "Erzkämmerer des Heiligen Römischen Reiches (Erkekammerer av Det Hellige Romerske Rike) var ett av de sju arveembetene i riket, tradisjonelt knyttet til kurfyrsten av Brandenburg. Embedet var primært seremonielt og ble utøvet ved keiserlige kroninger og høytidelige riksdager, der erkekammereren hadde ansvar for ceremonielle hofftjenester. Tittelen ga prestisje og symbolsk rang i det keiserlige hierarkiet."),
]


def main():
    import sys
    dry_run = "--dry-run" in sys.argv

    db = create_client(SUPABASE_URL, SUPABASE_SERVICE_KEY)

    print(f"Oppdaterer {len(UPDATES)} tittelgrupper ({sum(len(ids) for ids, _ in UPDATES)} rader)...\n")
    success = 0
    errors = 0

    for ids, description in UPDATES:
        if dry_run:
            print(f"  [dry-run] ville oppdatert {ids}: {description[:60]}...")
            continue
        try:
            for row_id in ids:
                db.table("person_roles").update({"reason": description}).eq("id", row_id).execute()
            print(f"  ✓ {ids}")
            success += 1
        except Exception as e:
            print(f"  ✗ {ids}: {e}")
            errors += 1

    if not dry_run:
        print(f"\nFerdig! {success} grupper oppdatert ({sum(len(ids) for ids, _ in UPDATES)} rader), {errors} feil.")
    else:
        print(f"\n[dry-run] Ville oppdatert {len(UPDATES)} grupper.")


if __name__ == "__main__":
    main()
